# Generated by Django 5.0.3 on 2024-03-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cate_id', models.IntegerField()),
                ('product_cate_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Price', models.IntegerField()),
                ('Product_Brand', models.CharField(max_length=100)),
                ('Product_Cate_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_cate')),
            ],
        ),
    ]
